version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    stdin_open: true
    tty: true
    command: python -Wd manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    links:
      - db
    environment:
      DEBUG: "true"
      SECRET_KEY: "not secure only use for development"
      DOCKER_HOST: "unix:///var/run/docker.sock"
      HOST_PWD: "${PWD}"
      GITHUB_ACCESS_TOKEN: "${GITHUB_ACCESS_TOKEN}"
      # Set these envvars in a .env file to test S3 in development
      MEDIA_USE_S3: "${MEDIA_USE_S3}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_STORAGE_BUCKET_NAME: "${AWS_STORAGE_BUCKET_NAME}"
      AWS_S3_REGION_NAME: "us-east-1"
      ENGRAFO_IMAGE: "${ENGRAFO_IMAGE}"
